const members = [
  {
    firstName: "John ",
    lastName: "Doe",
    jobTitle: "Software Engineer",
    department: "Engineering",
    manager: null,
    location: "Glasgow",
    firstAider: "No",
    userSlack: "johndoe",
    timezone: "America/Los_Angeles",
  },
  {
    firstName: "Jane",
    lastName: "Doe",
    jobTitle: "Software Engineer",
    department: "Engineering",
    manager: "John Doe",
    location: "Leeds",
    firstAider: "No",
    userSlack: "janedoe",
    timezone: "America/Los_Angeles",
  },
  {
    firstName: "Bob",
    lastName: "Doe",
    jobTitle: "Software Engineer",
    department: "Engineering",
    manager: "John Doe",
    location: "Cape Town",
    firstAider: "No",
    userSlack: "bobdoe",
    timezone: "America/Los_Angeles",
  },
  {
    firstName: "Sally",
    lastName: "Doe",
    jobTitle: "Software Engineer",
    department: "Engineering",
    manager: "John Doe",
    location: "Rome",
    firstAider: "No",
    userSlack: "sallydoe",
    timezone: "America/Los_Angeles",
  },
];

module.exports = members;
